<?php
/**
 * Refer to LICENSE.txt distributed with the Temando Shipping module for notice of license
 */

/**
 * @var \ReachDigital\GuestToShadowCustomer\Block\Adminhtml\SalesOrderViewInfo $block
 */
// @codingStandardsIgnoreFile
$order = $block->getOrder();
?>
<tr>
    <th><?= $block->escapeHtml(__('Shadow Customer:')) ?></th>
    <td><?= $block->escapeHtml($block->getIsShadowCustomer()) ?></td>
</tr>